### ISSUE TITLE
Deploying the Application

### ISSUE THREAD

**Issue by OpenBrazil** [codeforamerica/brigade#527]
The last update of instructions for deploying the application is Aug 4th 2013. 
Can you help me to deploy or can you update the wiki? https://github.com/codeforamerica/brigade/wiki#deploying-the-application

**Comment by OpenBrazil** [comment]
Any help?

**Comment by tdooner** [comment]
Hello. There's some documentation in the README: https://github.com/codeforamerica/brigade#install-node-yarn-and-webpack

Sorry that this app is poorly documented, it has evolved much over time (and the 2013 docs are probably quite out-of-date since the whole thing was rewritten in 2015).

If you hit a specific question, let me know. You might find it easier to start by trying to push it to Heroku, where most of the build logic comes for free.

**Comment by OpenBrazil** [comment]
Thank you Tom. 

I really want to deploy the brazilian brigade portal. Any issue I will ask for your help. Thank you very much.

Stephan

**Comment by tdooner** [comment]
Godspeed. Open this up if you have other questions.
